[2024-10-03T18:17:54.267+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T18:17:54.276+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag.preprocess_task manual__2024-10-03T12:47:50.991766+00:00 [queued]>
[2024-10-03T18:17:54.281+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag.preprocess_task manual__2024-10-03T12:47:50.991766+00:00 [queued]>
[2024-10-03T18:17:54.281+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-03T18:17:54.305+0530] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): preprocess_task> on 2024-10-03 12:47:50.991766+00:00
[2024-10-03T18:17:54.310+0530] {standard_task_runner.py:72} INFO - Started process 11718 to run task
[2024-10-03T18:17:54.313+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'prediction_dag', 'preprocess_task', 'manual__2024-10-03T12:47:50.991766+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/tmp/tmpe19ginzo']
[2024-10-03T18:17:54.315+0530] {standard_task_runner.py:105} INFO - Job 88: Subtask preprocess_task
[2024-10-03T18:17:54.378+0530] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag.preprocess_task manual__2024-10-03T12:47:50.991766+00:00 [running]> on host Nithesh-Kumar.localdomain
[2024-10-03T18:17:54.483+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prediction_dag' AIRFLOW_CTX_TASK_ID='preprocess_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T12:47:50.991766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T12:47:50.991766+00:00'
[2024-10-03T18:17:54.485+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T18:17:54.519+0530] {base.py:84} INFO - Retrieving connection 'target_***_conn'
[2024-10-03T18:17:54.553+0530] {logging_mixin.py:190} WARNING - /home/username/blackstraw/airflow/airflow/dags/prediction_dag.py:26 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-03T18:17:54.579+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/blackstraw/airflow/airflow/dags/prediction_dag.py", line 30, in preprocess_task
    preprocessed_data = preprocess(data, is_training=False)
  File "/home/username/blackstraw/house_prices/preprocess.py", line 16, in preprocess
    continuous_features_df = preprocess_continuous_features(dataframe, is_training)
  File "/home/username/blackstraw/house_prices/preprocess.py", line 30, in preprocess_continuous_features
    scaled_features_array = scaler.transform(dataframe[CONTINUOUS_FEATURE_COLUMNS])
  File "/home/username/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/username/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/username/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['TotRmsAbvGrd', 'WoodDeckSF', 'YrSold'] not in index"
[2024-10-03T18:17:54.591+0530] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag, task_id=preprocess_task, run_id=manual__2024-10-03T12:47:50.991766+00:00, execution_date=20241003T124750, start_date=20241003T124754, end_date=20241003T124754
[2024-10-03T18:17:54.616+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T18:17:54.616+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 88 for task preprocess_task ("['TotRmsAbvGrd', 'WoodDeckSF', 'YrSold'] not in index"; 11718)
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/blackstraw/airflow/airflow/dags/prediction_dag.py", line 30, in preprocess_task
    preprocessed_data = preprocess(data, is_training=False)
  File "/home/username/blackstraw/house_prices/preprocess.py", line 16, in preprocess
    continuous_features_df = preprocess_continuous_features(dataframe, is_training)
  File "/home/username/blackstraw/house_prices/preprocess.py", line 30, in preprocess_continuous_features
    scaled_features_array = scaler.transform(dataframe[CONTINUOUS_FEATURE_COLUMNS])
  File "/home/username/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/username/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/username/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['TotRmsAbvGrd', 'WoodDeckSF', 'YrSold'] not in index"
[2024-10-03T18:17:54.650+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T18:17:54.679+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T18:17:54.680+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
